### ISSUE TITLE
Modal component should not be in the React tree all the time

### ISSUE THREAD

**Issue by flexdinesh** [ruphaa/simple-react-modal#2]
https://github.com/ruphaa/simple-react-modal/blob/afe19660ebc86b6ca6209f7419bf7621a9c18483/src/components/Simple.js#L12

If `visible` prop is passed to the `Modal` component, then that component will be in the tree all the time. Instead use that prop to decide whether to render modal component or not.

Instead of

```jsx
...
<Modal visible={visible}>...</Modal>
```

Opt for conditional component rendering pattern —

```jsx
{visible && <Modal ...>...</Modal>}
```

**Comment by ruphaa** [comment]
Thanks, I've addressed your comment.
